name: GitHub Security Alerts for Jira

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.x
        env:
          GH_SECURITY_TOKEN: ${{ secrets.JAMESGITHUBSECRETS }}
          JIRA_TOKEN: ${{ secrets.JAMESJIRAAPI }}
          JIRA_HOST: https://at-harvard.atlassian.net
          JIRA_USER: james_jain-lynch@harvard.edu
          JIRA_PROJECT: LTSMAINT
          JIRA_ISSUE_TYPE: Security
          JIRA_WATCHERS: james_jain-lynch@harvard.edu
